openapi: 3.0.0
info:
  title: NswagDemo
  version: V1

paths:
  '/customer':
    post:
      tags:
        - "customer"
      summary: Add Customer
      description: Add Customer
      operationId: AddCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCustomer'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddCustomerResponse'

components:
  schemas:
    AddCustomer:
      type: object
      properties:
        FirstName:
          type: string
        LastName:
          type: string
          nullable: true
        Email:
          type: string

    AddCustomerResponse:
      type: object     
      properties:
        Success:
          type: boolean        
           